version: "3.9"

services:
  main:
    build:
      context: .
      dockerfile: ./docker/local/fastapi/DockerFile
    container_name: main
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "8001:80"
    networks:
      - main_proj
    
  postgres:
    image: postgres:13-alpine
    container_name: main_postgres
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - main_proj
    ports:
      - 54033:5432

networks:
  main_proj:
    driver: bridge

volumes:
  local_postgres_data: {}