#!/bin/bash

set -o errexit
set -o nounset


worker_ready(){
    celery -A config inspect ping
}

until worker_ready; do
    >&2 echo "Celery Workers are not available ..."
    sleep 1
done
>&2 echo "Celery Workers are available and ready ..."

celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler