version: "3.9"

services:
  admin:
    build:
      context: .
      dockerfile: ./docker/local/django/DockerFile
    command: /start
    container_name: admin
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - postgres
    networks:
      - admin_proj

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - admin_proj
    ports:
      - 54032:5432

networks:
  admin_proj:
    driver: bridge

volumes:
  local_postgres_data: {}
  static_volume:
  media_volume:
    