#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 /app/manage.py migrate --no-input
python3 /app/manage.py collectstatic --no-input
python3 manage.py runserver 0.0.0.0:8000
# /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app